server:
  port: 9090

spring:
  application:
    name: integration_dashboard


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789AbCdEfGhIjKlLmNoPqRsTuVwXyZ0123456789"